### ISSUE TITLE
License stuff

### ISSUE THREAD

**Issue by sofroniewn** [napari/cookiecutter-napari-plugin#1]
Looking very cool! Two quick things on licenses 

- can you update the license of the cookiecutter repo to be the same as the main napari repo BSD-3 and to napari - not a big deal, but I see no reason why not to be consistent here if it is fine with you

- and for the defaults on licenses the cookiecutter suggests could we have them be:
```
Select license:
1 - BSD-3
2 - MIT
3 - LPGL v3.0
4 - GNU GPL v3.0
```
where I swapped the order of BSD-3 and MIT, and added LGPL as one of the default options (I'd even drop GPL if people thought that was ok ....)

**Comment by AhmetCanSolak** [comment]
I do not think dropping GPL would be okay and it seems on various surveys MIT is the most popular choice, so maybe better to leave it at first place for convenience.

**Comment by jni** [comment]
Three notes:

- the Python community uses BSD 3-clause by default, so I think that's the most appropriate default.
- Sure, we can leave GPL, it's popular. Perhaps we can have a warning that we likely won't distribute the plugin as a bundle with napari if it is GPL.
- I would like to add MPL (Mozilla Public License) in the mix. @jakirkham pointed me to the license originally, and it fits in very strongly with my idea of fairness. I have come to see BSD/MIT as too permissive, but GPL and LGPL are in my opinion too restrictive. Summary of MPL: if you use the software, you must make any modifications you've made *directly to the software* available to others. Any code you develop that uses the software or links to it, you can do what you please with.

**Comment by AhmetCanSolak** [comment]
I have to say I disagree with @jni that python community uses BSD 3-clause by _default_. I just checked the most-starred open source python projects on github and there is a huge MIT(MIT-like) and Apache 2.0 dominance. This is such a minor decision but let's not deny realities.

Adding MPL sounds like a good idea @jni . I support that!
Adding a warning for GPL plugins make sense too.

**Comment by sofroniewn** [comment]
I think @jni is referring to the scientific python community which tends to use BSD-3, for example [numpy](https://github.com/numpy/numpy/blob/master/LICENSE.txt), [scipy](https://github.com/scipy/scipy/blob/master/LICENSE.txt), [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/master/COPYING), [scikit-image](https://github.com/scikit-image/scikit-image/blob/master/LICENSE.txt), [pandas](https://github.com/pandas-dev/pandas/blob/master/LICENSE) , and [pytorch](https://github.com/pytorch/pytorch/blob/master/LICENSE) all use BSD and I think we see napari as part of that scientific python ecosystem rather than the broader python community which may have other license preferences.
