### ISSUE TITLE
pyqt5 is needed in setup.cfg?

### ISSUE THREAD

**Issue by cnstt** [napari/cookiecutter-napari-plugin#108]
When I wanted to try and test my plugin in a fresh virtualenv, although napari and qtpy were installed through setup.cfg, napari couldn't start because of the lack of pyqt5. So I added it to the setup.cfg so when doing `pip install -e .` Napari could start!
Is this a bug with the cookiecutter plugin or am I doing something wrong?

**Comment by alisterburt** [comment]
Hi @cnstt, thanks for raising this issue!

This is a deliberate choice, pyqt5 has a license that is restrictive for certain groups of people and they may prefer to use pyside2, an alternative set of python bindings for Qt. We would prefer that plugin authors not depend on specific qt bindings for this reason.

A solution for your own plugin would be to add an [extras_require](https://github.com/napari/napari/blob/2648c307168fdfea7b5c03aaad4590972e5dfe2c/setup.cfg#L87-L165) section to your `setup.cfg` file which includes pyqt5. You can then install your package, with the bindings with a command like `pip install mypackage[all]`

Going to close this, feel free to reopen if you still think this is an issue

**Comment by tlambert03** [comment]
See also https://napari.org/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies
