### ISSUE TITLE
pre-commit is breaking the package

### ISSUE THREAD

**Issue by cnstt** [napari/cookiecutter-napari-plugin#121]
When running pre-commit, it deletes some imports in the init (of this package https://github.com/deep-finder/napari-deepfinder ) that are necessary for the testing to work properly:
```
from ._reader import napari_get_reader
from ._writer import write_annotations_xml
from ._widget import denoise_widget, reorder_widget, AddPointsWidget
from ._orthoview_widget import Orthoslice
```
Is this the wanted behaviour for pre-commit? Because maybe I using it the wrong way, but it is causing more damage than improvements for me currently ...

**Comment by Czaki** [comment]
this is a bug in cookiecutter fixed in #119 (not merged yet). This is problem of lack of `__all__` in `__init__`

**Comment by Czaki** [comment]
> Thanks a lot! Will there be a way to "update" a plugin afterwards with this change or is a manual intervention needed?

Based on my knowledge there is a need for manually fixing.

You need to add this line to `__init__.py`
```
__all__ = ("napari_get_reader", "write_annotations_xml", "denoise_widget", "reorder_widget", "AddPointsWidget", "Orthoslice")
```

**Comment by tlambert03** [comment]
Note on updating, we don’t have this in our docs, but if you use cruft instead of cookiecutter when starting the project, you can use it’s update feature

https://github.com/cruft/cruft

**Comment by tlambert03** [comment]
You can remove setup-cfg precommit if you’d like

**Comment by tlambert03** [comment]
Yep; you should feel free to add/remove anything you want to tune it to your liking

**Comment by Czaki** [comment]
> * the setup process of cookiecutter  "napari-foobar"

Maybe we should fix this

**Comment by tlambert03** [comment]
> the setup process of cookiecutter "napari-foobar"
Maybe we should fix thisfrom the pep you linked @Czaki:

> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.
