### ISSUE TITLE
Automatically generate a documentation

### ISSUE THREAD

**Issue by cnstt** [napari/cookiecutter-napari-plugin#124]
Maybe that could be a good thing, to generate a documentation automatically. What do you think about this? Maybe some kind of basic sphinx documentation?
Because I plan to do a documentation for my plugin, but thought maybe as I'm working on it I may also contribute to a more general approach for the cookiecutter template...

**Comment by tlambert03** [comment]
that action appears to publish docs to the `gh-pages` branch in a given repo.  which wouldn't help here?

Just to clarify, are you discussing making it so that "ready to go documentation" is part of the plugin after you create it?  or are you talking about docs for napari-cookie-cutter itself?

**Comment by tlambert03** [comment]
yeah, the maintenance burden I'm referring to is that if we a "prebaked" docs folder in this template (i.e. if we _run_ `sphinx-quickstart` once here for people). then those files that were autogenerated by sphinx will, themselves, go out of date eventually.   And we would essentially have to redo that process (or somehow automate it) periodically to keep it up to date.  The github action you're pointing to would simply _build_ already complete documentation into an html site and upload it to your repo (which isn't what we want here... we don't want to actually create a `gh-pages` branch here in this repo).

I know it's tempting to make these cookiecutters do "all the things" one could ever want out of a repo :) but in this case, given the complexities of actually doing documentation well, I think both we (the maintainers) and the end-users are better off going directly to the source here (i.e. go to sphinx or mkdocs or jupyter-book and follow their up-to-date tutorials).
