### ISSUE TITLE
Make default development status alpha

### ISSUE THREAD

**Issue by sofroniewn** [napari/cookiecutter-napari-plugin#13]
Should we make the default development status alpha? seems a lot to put it into alpha right off the bat - see https://github.com/napari/cookiecutter-napari-plugin/blob/cecf1a16cc8564520a51c075a1a8d9d82589e153/%7B%7Bcookiecutter.plugin_name%7D%7D/setup.py#L45

**Comment by jni** [comment]
👍 from me!

**Comment by tlambert03** [comment]
(been changed to pre-alpha)
