### ISSUE TITLE
task: move documentation on napari-hub/description.md to hub wiki

### ISSUE THREAD

**Issue by tlambert03** [napari/cookiecutter-napari-plugin#132]
@potating-potato, I think it would make more sense to put the long instructions in `description.md` on the hub wiki page, in a section describing best practices on customizing a listing on the hub.  There, it would be easier to customize, and keep up to date, and would stay relevant long after someone had cloned this cookiecutter repo.

The description.md here could just have a link to those docs.  thoughts?

**Comment by potating-potato** [comment]
By description.md are you referring to https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/.napari-hub/DESCRIPTION.md?

supposedly it is a placeholder that the plugin owner would modify to add the description they would like to have.

Do you mean we would drop this placeholder file and add a link (I assume in the cookie-cutter readme?) to the hub wiki instead to explain how to add a customized description?

**Comment by tlambert03** [comment]
> Do you mean we would drop this placeholder file and add a link (I assume in the cookie-cutter readme?) to the hub wiki instead to explain how to add a customized description?

no, the placeholder file would stay... but it would just have much less text in it, mostly just providing a link like "for tips on how to leverage this file to customize how your page looks on the hub, see <some link>".  That way you can keep it up to date, and iterate, and long after someone has cloned this repo it would still be modern and useful for them

**Comment by potating-potato** [comment]
Ohh I was confused because I didn't realize there is much more content than what GitHub displays.

```
The developer has not yet provided a napari-hub specific description.
```

that makes sense, I can take care of this
