### ISSUE TITLE
Setup.py python_requires >=3.7

### ISSUE THREAD

**Issue by sofroniewn** [napari/cookiecutter-napari-plugin#14]
Should we now make the setup.py python_requires >=3.7, see https://github.com/napari/cookiecutter-napari-plugin/blob/cecf1a16cc8564520a51c075a1a8d9d82589e153/%7B%7Bcookiecutter.plugin_name%7D%7D/setup.py#L40

**Comment by jni** [comment]
👍 from me

**Comment by tlambert03** [comment]
Yep!

**Comment by Czaki** [comment]
Already done
