### ISSUE TITLE
Github CI error with `DISPLAY XAUTHORITY`

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#146]
Hi all,

I'm receiving errors in github CI on multiple plugins presuming something upstream broke. Example:
https://github.com/haesleinhuepf/napari-skimage-regionprops/actions/runs/3924350395/jobs/6708551176

```
Command: python -m tox
/usr/bin/xvfb-run --auto-servernum python -m tox
py310-linux: failed with pass_env values cannot contain whitespace, use comma to have 
multiple values in a single line, invalid values found 'DISPLAY XAUTHORITY'
```

Removing this line fixes the issue but I have no idea about side-effects:

https://github.com/napari/cookiecutter-napari-plugin/blob/adf539fe5413c9187c5e5dc2e3bd51adea8eaf71/%7B%7Bcookiecutter.plugin_name%7D%7D/tox.ini#L26

Best,
Robert

**Comment by Czaki** [comment]
> Removing this line fixes the issue but I have no idea about side-effects:

it may crash your tests when running GUI test on linux. 

Since tox 4 its no longer accepts Two variables in one line. You should split it into two lines. See: https://github.com/napari/napari/pull/5441

**Comment by haesleinhuepf** [comment]
Awesome. Thanks for the lightspeed response @Czaki !
