### ISSUE TITLE
Move from setup.py to setup.cfg

### ISSUE THREAD

**Issue by sofroniewn** [napari/cookiecutter-napari-plugin#15]
Should we move from setup.py to setup.cfg like the main repo has done? The symmetry would help me understand better how to do things like add testing only dependencies, something that came up in the context of napari-console

**Comment by jni** [comment]
Yeah, that's the more modern way. Some projects don't even ship a setup.py anymore, though we shouldn't do that, because it breaks not-that-old versions of pip 😂

**Comment by tlambert03** [comment]
fine with me.  originally I opted for `setup.py` since I thought it would be more recognizable to "newcomers", and having the nearly empty `setup.py` (in addition to a `setup.cfg`) might have been confusing... (Though necessary, as @jni points out)

**Comment by sofroniewn** [comment]
@DragaDoncila can this be closed by #31?

**Comment by DragaDoncila** [comment]
Yep, looks like it @sofroniewn
