### ISSUE TITLE
`setup.cfg` version metadata field vs `__init__.py` `__version__` value

### ISSUE THREAD

**Issue by dalthviz** [napari/cookiecutter-napari-plugin#155]
Hi, doing an initial release for [a plugin](https://github.com/dalthviz/napari-ui-tracer), that used the cookiecutter to generate its initial structure, I noticed that the `setup.cfg` version doesn't use the `__version__` value available at `__init__.py`. [I fixed that on the plugin](https://github.com/dalthviz/napari-ui-tracer/commit/f7125a230eade255fdb8bb710f0e33039785bfc0) by changing:

https://github.com/napari/cookiecutter-napari-plugin/blob/d0c893f586c6c041d1d362eedfa7b85f6613a900/%7B%7Bcookiecutter.plugin_name%7D%7D/setup.cfg#L4

To

```python
version: attr: napari_ui_tracer.__version__
```

Which as a template I think it should be something like:

```python
version: attr: {{cookiecutter.module_name}}.__version__
```

Is that the correct approach and a fix to do here?

**Comment by Czaki** [comment]
No. Plugin uses setuptools_scm to determine version. And setuptools_scm both generate _version.py and update plugin metadata.

**Comment by dalthviz** [comment]
Maybe I experienced this because I didn't use the `use_git_tags_for_versioning` option which caused the plugin to not get the related `setuptools_scm` stuff?

https://github.com/napari/cookiecutter-napari-plugin/blob/d0c893f586c6c041d1d362eedfa7b85f6613a900/%7B%7Bcookiecutter.plugin_name%7D%7D/setup.cfg#L3-L5

Just double checking, but if the change explained in the OP is not necessary feel free to close this :+1:

**Comment by Czaki** [comment]
Ok. You are correct. I miss this variant. I think that it should be fixed.
