### ISSUE TITLE
Packaging: remove setup.cfg and move info into pyproject.toml

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/cookiecutter-napari-plugin#167]
Now that [pyproject.toml supports project metadata](https://peps.python.org/pep-0621/) (classifiers, author info, etc.) we should remove the [setup.cfg](https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/setup.cfg) file and put the information into [pyproject.toml](https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/pyproject.toml)

Advantages:
* simplifies the repository
* It makes it much easier for users to retro-fit napari plugins to existing 
* it discourages people from accidentally duplicating info across both pyproject.toml and setup.cfg (if this happens pyproject.toml overwrites the information). 
    * For an in the wild example of this problem, Draga and I got an email from some users confused about why their plugin was not being picked up by the napari hub. It turned out that they had classifier tags in both pyproject.toml AND setup..cfg, and so the napari framework tag was not being included in the packaged build (and therefore not available on PyPI for the napari-hub to discover it)

**Comment by Czaki** [comment]
lets do this :)
