### ISSUE TITLE
Deprecated linter settings in `pyproject.toml`

### ISSUE THREAD

**Issue by AJFSalomon** [napari/cookiecutter-napari-plugin#176]
When I run pre-commit on my cookiecutter-based Napari plugin project, ruff issues the following warning:

```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
  - 'ignore' -> 'lint.ignore'
  - 'select' -> 'lint.select'
```

I've made the suggested changes to my project, but thought I'd file this quick issue so that the cookiecutter can also be updated accordingly.

**Comment by jni** [comment]
Thanks for pointing this out @AJFSalomon! If you have the time/capacity to make a PR to change this in the cookiecutter, it would be appreciated, but if not, that's ok too, we'll aim to implement a fix shortly. 🙏

**Comment by AJFSalomon** [comment]
> Thanks for pointing this out @AJFSalomon! If you have the time/capacity to make a PR to change this in the cookiecutter, it would be appreciated, but if not, that's ok too, we'll aim to implement a fix shortly. 🙏

Just made the requested pull request 🙂 This is my first PR on GitHub, so feel free to tell me if anything is missing 😉

**Comment by jni** [comment]
> This is my first PR on GitHub

wow! Sorry for my lackadaisical suggestion, it's always hard to know what level of experience people are coming from without the risk of sounding condescending. But anyway it looks good to me! Having said this I'm not actually that familiar with the test setup of this repo, so it's possible some tests would fail, in which case, we would need to fix them. This can be done by just pushing more commits to the PR branch. But for now, it looks good! 😊 Thanks! 🙏

**Comment by AJFSalomon** [comment]
> wow! Sorry for my lackadaisical suggestion, it's always hard to know what level of experience people are coming from without the risk of sounding condescending. But anyway it looks good to me! Having said this I'm not actually that familiar with the test setup of this repo, so it's possible some tests would fail, in which case, we would need to fix them. This can be done by just pushing more commits to the PR branch. But for now, it looks good! 😊 Thanks! 🙏

Looks like all the tests passed!

Anyway, no problem with your suggestion, it was a good learning opportunity 😉

**Comment by jni** [comment]
Welcome to the project! 😃
