### ISSUE TITLE
`{{cookiecutter.plugin_name}}/README.md` conditional sections renders wrong

### ISSUE THREAD

**Issue by lucyleeow** [napari/cookiecutter-napari-plugin#178]
There are 2 conditional sections in `{{cookiecutter.plugin_name}}/README.md` that seem to render wrong, see: https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/README.md?

![image](https://github.com/napari/cookiecutter-napari-plugin/assets/23182829/e1b2330f-f17f-445f-a333-d8ec76607eda)

and 

![image](https://github.com/napari/cookiecutter-napari-plugin/assets/23182829/72ae73fe-3cbc-4159-a3dc-ab2dda504225)

are these meant to look like this?

**Comment by DragaDoncila** [comment]
yeah I think these are supposed to look like this. If you build a plugin using the cookiecutter, the template bits should be replaced with just the actual text.

**Comment by lucyleeow** [comment]
Ok thanks!
