### ISSUE TITLE
Implement useful error message for original `cookiecutter` command

### ISSUE THREAD

**Issue by DragaDoncila** [napari/cookiecutter-napari-plugin#191]
Once this repo is renamed and the `napari-plugin-template` is live, we should implement a meaningful error message for when someone tries to run the old command, referencing the `cookiecutter-napari-plugin` repo. 

Perhaps we remake the cookiecutter repo after renaming this one, and have it throw a meaningful error, or perhaps we rely on GitHub's redirect and just add the dummy cookiecutter config with the error message?

**Comment by GenevieveBuckley** [comment]
> Perhaps we remake the cookiecutter repo after renaming this one, and have it throw a meaningful error, or perhaps we rely on GitHub's redirect and just add the dummy cookiecutter config with the error message?

Yeah, maybe. We'll have to check what the easiest way to generate a good error message with cookiecutter is
