### ISSUE TITLE
Should this repo be archived using the GitHub interface

### ISSUE THREAD

**Issue by willingc** [napari/cookiecutter-napari-plugin#194]
Readme states the repo is archived. Do you want to archive the repo in the GitHub UI?

**Comment by DragaDoncila** [comment]
Good point, @jni @melissawm afaik the `napari-plugin-template` is ready to go right, so we should be able to archive this repo without any impact?

**Comment by jni** [comment]
I think we were waiting for #191, but maybe it's not needed...

**Comment by jni** [comment]
> If we archive it can it no longer be used by cookiecutter?

it *can* be used, but read-only = no pushes (afaik), so we could no longer fix with your suggestion:

> I think the easiest way to address it would be to have the pre_gen_project.py hook raise an error that points to the napari plugin template?

yes I think that's right

**Comment by willingc** [comment]
> I think the easiest way to address it would be to have the pre_gen_project.py hook raise an error that points to the napari plugin template?

Perhaps use the [`pre_prompt.py` hook](https://github.com/cookiecutter/cookiecutter/blob/b4451231809fb9e4fc2a1e95d433cb030e4b9e06/docs/advanced/hooks.rst#types-of-hooks) since it runs before `pre_gen_project.py` and can bail before the cookie-cutter prompting.

**Comment by DragaDoncila** [comment]
Opened #195 to address!

**Comment by jni** [comment]
#195 is merged, I'm going to close this and archive. Thanks for the prod @willingc!
