### ISSUE TITLE
pypi deployment fails in freshly cutted plugins on windows 

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#27]
Hi all, hi @tlambert03 ,

while fixing a [deployment bug in a napari plugin](https://github.com/clEsperanto/napari_pyclesperanto_assistant/issues/21) it became apparent, that the cookiecutter template `setup.py` contains some stuff that breaks deployment. Maybe this is a Windows-only issue. The bug could be fixed by replacing [this line](https://github.com/napari/cookiecutter-napari-plugin/blob/33ba36fd3b023e10901a2d6a27c595f12ee9aa50/%7B%7Bcookiecutter.plugin_name%7D%7D/setup.py#L37) with something like this:

```
with open("README.md", "r") as fh:
    long_description = fh.read()

# ....

long_description=long_description,
```

If #26 is implemented, this issue may become obsolete anyway.

Let me know if I can help in any way.

Best,
Robert

**Comment by GenevieveBuckley** [comment]
Huh, I don't think anyone realized that could cause a problem. 

Yes, go ahead and submit a PR with your suggested fix. There's no need to wait for https://github.com/napari/cookiecutter-napari-plugin/issues/26, although if you wanted to jump straight to that endpoint that'd be fine too.

**Comment by tlambert03** [comment]
I think most people might be using the deployment method described in the readme, which runs on GitHub actions with Linux (on a tagged commit).  So it's possible it's just now being tried on windows!

**Comment by haesleinhuepf** [comment]
I also think the number of Windows users is yet small among plugin developers ;-)

**Comment by haesleinhuepf** [comment]
This is resolved since https://github.com/napari/cookiecutter-napari-plugin/commit/c7d5b8a209e578f2222ad51c3835a24e6d4c68e6
