### ISSUE TITLE
Napari crashes in freshly created plugins when selecting a function widget form the menu

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#28]
Hi all, 

I just created a new [function-based plugin](https://github.com/haesleinhuepf/napari-image-quality-analyzer/commits/master) using the cookiecutter. When selecting "threshold" from the menu, napari crashes. I just closes without any error message or stdout/stderr output. I observed the same issue earlier with napari 0.4.7, a colleague confirmed the same problem on another computer (also Windows 10) and I face the same issue now also with napari 0.4.8-rc1. The issue can be solved by changing this:
https://github.com/haesleinhuepf/napari-image-quality-analyzer/commit/37ff1f5729e6962994ec1cd16d7699245b08245b

Thus, I assume there is something wrong with `TYPE_CHECKING` and parameter types as string. My napari info follows below.

Let me know if I can help tracing down this issue!

Best,
Robert

napari: 0.4.8rc1
Platform: Windows-10-10.0.19041-SP0
Python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 04:59:43) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.2
Dask: 2021.04.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8681
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- clEsperanto: 0.8.0
- console: 0.0.3
- napari-image-quality-analyzer: 0.1.0
- napari-skimage-regionprops: 0.0.0
- napari_webcam: 0.1.17
- scikit-image: 0.4.8rc1
- svg: 0.1.4

**Comment by tlambert03** [comment]
Thanks for reporting, can you try something for me?

Use the fully qualified name for the type annotation, `"napari.types.ImageData"`. And then in TYPE_CHECKING just "import napari"
