### ISSUE TITLE
issue with scm

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#33]
Hi all, 
CC @CamachoDejay

I'm having issues with the scm stuff in the cookie cutter template. When following all git-related instructions, I end up with a repository on github.com. And that's great! When I then create a release and share it with a colloaborator asking them to install it, we see an error popping up in their napari. That's the link:
https://github.com/CamachoDejay/smart-microscopy-minimal/archive/refs/tags/0.1.0.zip

I install it like this:
![image](https://user-images.githubusercontent.com/12660498/119120876-1398ae80-ba2d-11eb-9df0-100ebf37ef87.png)

And the error is this one:
```
Collecting https://github.com/CamachoDejay/smart-microscopy-minimal/archive/refs/tags/0.1.0.zip

  Downloading https://github.com/CamachoDejay/smart-microscopy-minimal/archive/refs/tags/0.1.0.zip

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\rober\miniconda3\envs\bio2\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Windows\\Temp\\pip-req-build-jjhu2g8f\\setup.py'"'"'; __file__='"'"'C:\\Windows\\Temp\\pip-req-build-jjhu2g8f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Windows\Temp\pip-pip-egg-info-05lxnw92'
         cwd: C:\Windows\Temp\pip-req-build-jjhu2g8f\
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Windows\Temp\pip-req-build-jjhu2g8f\setup.py", line 9, in <module>
        setup(
      File "c:\users\rober\miniconda3\envs\bio2\lib\site-packages\setuptools\__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\rober\miniconda3\envs\bio2\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\rober\miniconda3\envs\bio2\lib\site-packages\setuptools\dist.py", line 429, in __init__
        _Distribution.__init__(self, {
      File "c:\users\rober\miniconda3\envs\bio2\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\users\rober\miniconda3\envs\bio2\lib\site-packages\setuptools\dist.py", line 721, in finalize_options
        ep(self)
      File "c:\users\rober\miniconda3\envs\bio2\lib\site-packages\setuptools\dist.py", line 728, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\windows\temp\pip-req-build-jjhu2g8f\.eggs\setuptools_scm-6.0.1-py3.8.egg\setuptools_scm\integration.py", line 24, in version_keyword
        dist.metadata.version = _get_version(config)
      File "c:\windows\temp\pip-req-build-jjhu2g8f\.eggs\setuptools_scm-6.0.1-py3.8.egg\setuptools_scm\__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "c:\windows\temp\pip-req-build-jjhu2g8f\.eggs\setuptools_scm-6.0.1-py3.8.egg\setuptools_scm\__init__.py", line 134, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for 'C:\\Windows\\Temp\\pip-req-build-jjhu2g8f'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------

WARNING: Discarding https://github.com/CamachoDejay/smart-microscopy-minimal/archive/refs/tags/0.1.0.zip. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

This change fixes it:
https://github.com/CamachoDejay/smart-microscopy-minimal/commit/7dd8917ff2d89fb82b9a1073a32ed9dadc1db293
And I'm doing this change often.

Afterwards, installation works as you can see by installing https://github.com/CamachoDejay/smart-microscopy-minimal/archive/refs/tags/0.1.1.zip

Is there an official way to deliver a plugin to collaborators without this scm-stuff? Let's say I don't want to put my plugin on pypi and my git-skill-level is limited, but I do know python, napari and image processing well and I would like to share a plugin with a collaborator ;-)

Thanks!

Cheers,
Robert

**Comment by jni** [comment]
Hmm, good point. Sorry about that @haesleinhuepf, I think I pushed @tlambert03 to make the switch to scm.

Two options:

- @tlambert03 @haesleinhuepf does it work to point to a tag instead of a release zip?
- @tlambert03 would it be possible/easy to add a question to the cookiecutter, e.g. "do you want to use git to manage versions, or a string inside the setup file?"

**Comment by haesleinhuepf** [comment]
> does it work to point to a tag instead of a release zip?

No, unfortunately, not:
```
Collecting https://github.com/CamachoDejay/smart-microscopy-minimal/releases/tag/0.1.0

  Downloading https://github.com/CamachoDejay/smart-microscopy-minimal/releases/tag/0.1.0

  ERROR: Cannot unpack file C:\Windows\Temp\pip-unpack-yzbuignt\0.1.0 (downloaded from C:\Windows\Temp\pip-req-build-b4qqqm5u, content-type: text/html; charset=utf-8); cannot detect archive format

ERROR: Cannot determine archive format of C:\Windows\Temp\pip-req-build-b4qqqm5u
```

I think it's cool to have scm and git stuff in the template. It's just, if it doesn't work from scratch, it might detract the one or other napari-plugin-development-beginner ;-)

The CI for example also doesn't work usually:
```
  ERROR: InvocationError for command /home/runner/work/smart-microscopy-minimal/smart-microscopy-minimal/.tox/py38-linux/bin/pytest -v --color=yes --cov=smart_microscopy_minimal --cov-report=xml (exited with code 5)
```

https://github.com/CamachoDejay/smart-microscopy-minimal/commits/main

**Comment by tlambert03** [comment]
This has nothing to do with scm.  that's just not how you install something from github using pip.  (that line in the plugin installer there accepts anything that you could do with `pip install ____` ...)

The answer is there in your error message:
```
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

so, to install this package from a url, use:
```
git+https://github.com/CamachoDejay/smart-microscopy-minimal.git
```

or for a specific version:
```
git+https://github.com/CamachoDejay/smart-microscopy-minimal.git@0.1.0
```

more tips on installing with pip from github here: https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Comment by tlambert03** [comment]
note, you can also run `python setup.py bdist_wheel` and they can drop that wheel file into the installer line.

**Comment by jni** [comment]
@tlambert03 does our bundle ship with a fully functioning git???

**Comment by tlambert03** [comment]
dunno, but that's something to check.

**Comment by tlambert03** [comment]
> I think it's cool to have scm and git stuff in the template. It's just, if it doesn't work from scratch, it might detract the one or other napari-plugin-development-beginner ;-)

@haesleinhuepf, if it doesn't work from scratch.  it's not a detraction, it's a bug!  Literally the only thing that someone needs to do to make sure that version control is working is to run `git init` on their repo.  If the CI is not running, that's an independent problem and should be addressed

**Comment by haesleinhuepf** [comment]
> Literally the only thing that someone needs to do to make sure that version control is working is to run git init on their repo.

... if you have git installed. 

> git+https://github.com/CamachoDejay/smart-microscopy-minimal.git

A great hint! It's just as usual: Peope who don't use git from command line, receive an error. Btw napari 0.4.7 didn't come with git:
```
Collecting git+https://github.com/CamachoDejay/smart-microscopy-minimal.git

  Cloning https://github.com/CamachoDejay/smart-microscopy-minimal.git to c:\windows\temp\pip-req-build-5ctmsm9n
  Running command git clone -q https://github.com/CamachoDejay/smart-microscopy-minimal.git 'C:\Windows\Temp\pip-req-build-5ctmsm9n'

  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/CamachoDejay/smart-microscopy-minimal.git 'C:\Windows\Temp\pip-req-build-5ctmsm9n'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the 'C:\Users\rober\AppData\Local\Programs\napari\python\python.exe -m pip install --upgrade pip' command.

```

**Comment by jni** [comment]
>   ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/CamachoDejay/smart-microscopy-minimal.git 'C:\Windows\Temp\pip-req-build-5ctmsm9n'
> ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

That's what I feared...!

**Comment by tlambert03** [comment]
> ... if you have git installed.

if you're building from cookiecutter and uploading to github, I don't think it's too much to ask of our plugin developers that they have git installed???

**Comment by jni** [comment]
it's not for a developer @tlambert03

**Comment by haesleinhuepf** [comment]
I'm really just trying to lower the entrance burden

**Comment by jni** [comment]
if I understand the use case correctly, it's:

- developer makes little plugin that is for "local lab" use only, doesn't really feel they should upload to pypi
- they put it on github for their colleagues to use
- Now their colleagues need git in addition to the napari bundled app?

**Comment by haesleinhuepf** [comment]
Correct

**Comment by tlambert03** [comment]
> it's not for a developer @tlambert03

there's two separate issues here (for one you need git, for the other you shouldn't)

1) installing from the bundle (yes that needs to be fixed if you don't have git, we aren't making any assumptions about the user environment) in the meantime, email them a wheel with the `setup.py bdist_wheel` tip I mentioned
2) scm in the plugin cookiecutter... there it _is_ for a developer and they should use git

**Comment by haesleinhuepf** [comment]
> they should use git

I agree, but they should not be forced to.

**Comment by tlambert03** [comment]
yes, that's the part that needs fixing.  again, none of this has anything to do with the plugin developer, or the cookiecutter.

**Comment by tlambert03** [comment]
> I agree, but they should not be forced to.

The whole point of a cookiecutter is to make some assumptions.  They're not forced to do anything.   It's just a boilerplate.  They're not forced to use github actions, but it's set up for them (they could switch to travis).  They're not forced to use git but it's set up for them (they could switch to... snv?).

Installing from URL in the bundled app is a completely seperate issue here

**Comment by jni** [comment]
@tlambert03 but why not give them the option to not use setuptools_scm at all? Just like we give them the option to use GPL even though it's a terrible idea :joy:

**Comment by tlambert03** [comment]
that would be fine too!

**Comment by tlambert03** [comment]
(but it wouldn't fix any of the things going on here ... you all see that right?)

**Comment by jni** [comment]
sorry, my point is: we could set them up with the old-fashioned way, based on a new question during the cookiecutter setup process.

**Comment by haesleinhuepf** [comment]
> (but it wouldn't fix any of the things going on here ... you all see that right?)

If scm is deactivated, the installation would work

**Comment by jni** [comment]
> (but it wouldn't fix any of the things going on here ... you all see that right?)

Huh? @haesleinhuepf literally showed that if you hardcode the version number, installing from the github zip works

**Comment by jni** [comment]
here: https://github.com/CamachoDejay/smart-microscopy-minimal/commit/7dd8917ff2d89fb82b9a1073a32ed9dadc1db293

**Comment by tlambert03** [comment]
for that one repository!  if we want people to be able to install from `git+https` _in the napar app_ we need to ship with git.

**Comment by jni** [comment]
that's not this issue. This issue is about pip installing with https:, not git.

**Comment by tlambert03** [comment]
ok, you're saying you don't want to be able to install without the git+ prefix?

**Comment by jni** [comment]
We can raise a separate issue about how we can't install *any* of our plugins using setuptools_scm from github. But for all plugins that don't use setuptools_scm (which could be ~all of them if we so choose), installing from https would be fine, and would solve @haesleinhuepf's issue.

**Comment by tlambert03** [comment]
sure, that's fine with me

**Comment by jni** [comment]
> ok, you're saying you want to be able to install without the git+ prefix?

No, I'm saying, ok, patching this masks a much bigger missing feature, but that's a different bug/issue.

Also, just checked, git is GPL, so we *can't* ship it in our bundle. :facepalm:

**Comment by haesleinhuepf** [comment]
This turns out to be more complicated than I expected 🙂
