### ISSUE TITLE
Requirements.txt versus list in setup.cfg

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#40]
Hi all, 

just a quick question: At the moment, the template contains two ways for specifying dependencies: In the setup.cfg and in requirements.txt. Is this the typical way of doing this? I was just a bit confused where I need to enter the dependencies which get installed together with my napari plugin: It's in setup.cfg. So why is the requirements.txt there as well?

Thanks!

Best,
Robert

**Comment by jni** [comment]
I think at this point requirements.txt is a historical artifact. As far as I know it can be removed, although some tools / old-school users will look at it. In napari, therefore, we have a requirements.txt that merely points to the setup.cfg:

https://github.com/napari/napari/blob/a709e2fff035d5b19b9c3f1a870858a08dd60e33/requirements.txt

I would consider that to be the canonical way going forward.

**Comment by tlambert03** [comment]
Yeah this repo is setup like napari with just the `-e .` pointer... however, we don't have the useful comment explaining it here in requirements.txt.  We should add that
