### ISSUE TITLE
Drop use_git_tags_for_versioning choice

### ISSUE THREAD

**Issue by sofroniewn** [napari/cookiecutter-napari-plugin#46]
I was just creating a new plugin and saw `use_git_tags_for_versioning` in the cookiecutter as a choice. I have no idea what that means/ why i would/ wouldn't want to do that and I suspect most of our plugin devs won't either. Having an option there which folks don't understand I think creates unnecessary anxiety/ uncertainty.

I like the bevahiour we have of `git tag` to create a version release and then push the tag. Does that mean I wan't this to be `y`? But I see the default here is `n`. Advice on what I should do to keep consistency with behaviour before this became a choice would be appreciated.

Also I think we should then just stick with one option rather than give folks the choice, unless there are really compelling reasons to do so.

Thoughts @tlambert03 @jni?

**Comment by tlambert03** [comment]
That was added by request in https://github.com/napari/cookiecutter-napari-plugin/pull/34

I think @jni and @haesleinhuepf would have to weigh in on this

**Comment by sofroniewn** [comment]
Ok I just read through #33 and see https://github.com/napari/cookiecutter-napari-plugin/issues/33#issuecomment-845922103 from @jni where making this optional was suggested.

I think I disagree with the choice here @jni - I think adding this as optional is now putting a burden on every else in the community and causes unnecessary differences between plugins

I really agree with @tlambert03 here https://github.com/napari/cookiecutter-napari-plugin/issues/33#issuecomment-845921332 and would like us to consider reverting this change.

If we don't fight the impulse to just add options things quickly become unwieldy and confusing and put people off.

If you want to do something special, that's fine - but then tools like the cookiecutter probably aren't right for you or you might need to make custom modifications after starting with a cookiecutter template

**Comment by jni** [comment]
I don't feel super strongly about this, but I do think it's a significant usability bug of setuptools_scm that you can't install a package *at all* without a git repo. If you see the top of the issue, packages using setuptools_scm can't be installed from stock standard https .zip archives of github tagged releases. I find that pretty terrible!

I say this as someone who recently strongly advocated for skimage to move *to* using setuptools_scm. But I think big complex packages like skimage are a different ballgame to small one-purpose, maybe even one-lab plugins. I think we should support the small tinkerers with this repo, not just the big projects that probably have more experience managing this sort of thing. setuptools_scm tries to make a "one source of truth" and tries to hide a lot of complexity from users, but #33 shows that it does not always do a good job of that. Everyone understands a single string in the repo one can update to make new versions.

**Comment by sofroniewn** [comment]
Ok well, as an interim solution we should at least have somewhere that documents all the cookiecutter questions and what they mean, we could also maybe include a brief description of this one in the cookiecutter too. Maybe @DragaDoncila could work on this?

**Comment by DragaDoncila** [comment]
Happy to document the different options and what their repercussions may be - could be indispensable for users completely new to packaging

**Comment by haesleinhuepf** [comment]
Just my 2 cents: I do have strong opinions on this because I think people should not be forced to learn git in order to make napari plugins. :-) You know, there are excellent python image analysis programmers who are not so familiar with the command line and/or git. Thus, I'd be happy if using `git tag etc` would stay optional.

I would offer to write a tutorial on how to version/deploy a napari plugin using github desktop if you think that's a good idea. However, I would need support from you guys because I haven't managed the deployment via github-actions yet.

**Comment by sofroniewn** [comment]
Yup, your points are fair @haesleinhuepf.

We could also one day support a question "would you like to see advanced options" and then show more things like this under the advanced options - i'm not actually sure that's possible with cookiecutter, just assuming so :-)

> Happy to document the different options and what their repercussions may be - could be indispensable for users completely new to packaging

but for now fine to just add some docs somewhere explaining what options are, so that would be much appreciated @DragaDoncila!! thanks!!

**Comment by tlambert03** [comment]
> i'm not actually sure that's possible with cookiecutter, just assuming so :-)

Sadly nope
