### ISSUE TITLE
add `pre-commit-conifg.yaml`

### ISSUE THREAD

**Issue by ianhi** [napari/cookiecutter-napari-plugin#62]
I think it would be nice to have a `.pre-commit-config.yaml` file pre-populated for you.

I would suggest basing it off, or even copying: https://github.com/ianhi/pyrepo-cookiecutter/blob/ian/%7B%7Bcookiecutter.project_name%7D%7D/.pre-commit-config.yaml

**Comment by tlambert03** [comment]
i'd be for that.  wanna make a PR?  I think mypy _might_ be a bit much by default.  so perhaps comment that out?
