### ISSUE TITLE
napari docs for npe2 cookiecutter not matching reality

### ISSUE THREAD

**Issue by guiwitz** [napari/cookiecutter-napari-plugin#73]
I just wanted to clarify a comment I made on [Zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/npe2.20migration.20questions) about the documentation for getting started (https://napari.org/plugins/stable/npe2_getting_started.html#create-the-project-using-cookiecutter). The docs says:
> When the cookiecutter asked to include a reader plugin, we selected y, and in the next question we told cookiecutter that our reader should be invoked for files matching the *.npy glob pattern.

However, when I used the cookiecutter I never got asked that "next question". It simply defaulted to the ```npy``` case. If it's really planned to support choosing the import format in the cookiecutter that would very cool. If not I guess the above sentence should be removed form the napari docs (or clarified if I misunderstood).

**Comment by nclack** [comment]
I'm fixing the docs thanks to you!

> choosing the import format in the cookiecutter that would very cool

Even though the cookiecutter prompts don't ask you for it, you can (and should) edit the `napari.yml` file to add `filename_patterns` that your reader will recognize.

We initially had that prompt in the cookiecutter, but removed it to keep the prompts from getting too cluttered.
