### ISSUE TITLE
prefer `.yaml` to `.yml` in npe2 cookiecutter

### ISSUE THREAD

**Issue by nclack** [napari/cookiecutter-napari-plugin#76]
Surfacing this from the quoted discussion:

> We should decide what convention we're going to use. I've generally been going with `napari.yaml`.  YAML [prefers (https://yaml.org/faq.html) we use `.yaml` over `.yml`

_Originally posted by @tlambert03 in https://github.com/napari/cookiecutter-napari-plugin/pull/74#discussion_r772710472_

**Comment by sofroniewn** [comment]
I'm fine with `.yaml`. Once we make change we'll just need to make sure to update docs etc to be consistent
