### ISSUE TITLE
precommits are installed also if the user chooses not to install it

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#77]
Hi all,

I just used the cookiecutter to create another napari plugin. While going through the questions, I answered to 'install_precommit [n]:' with 'n'. Afterwards, it anyway installed precommit:

![image](https://user-images.githubusercontent.com/12660498/147146569-cb357d08-886f-4888-9e64-0e706b57c6ec.png)

I then deleted `.pre-commit-config.yaml`. Now, I see an error in github desktop:

![image](https://user-images.githubusercontent.com/12660498/147146384-5bfe4491-8fb4-44b3-9f78-e0de39f2afdb.png)

It would be nice if the pre-commits would not be installed if the users choooses so.

**Comment by tlambert03** [comment]
this is getting fixed in https://github.com/napari/cookiecutter-napari-plugin/pulls

**Comment by nclack** [comment]
I thought I had fixed it in #75 ... but I seem to have missed. trying again...

**Comment by haesleinhuepf** [comment]
Thanks for the rapid response @tlambert03 and @nclack 🌞

Happy Holidays! 🎄
