### ISSUE TITLE
Add new trove classifier for napari plugins to the cookiecutter

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/cookiecutter-napari-plugin#8]
Now there is a Trove classifier for napari plugins, we should add the classifier to this cookiecutter.

Ref: https://github.com/pypa/trove-classifiers/pull/53#event-3906296259

**Comment by jni** [comment]
So good! 🎉 

In the same vein, the name of the package should no longer default to `napari-`, since we don't need to rely on that for discoverability anymore.

**Comment by GenevieveBuckley** [comment]
This is a good one for a "good first issue" label
