### ISSUE TITLE
Question: Why are tests shipped with plugin code

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#87]
Hi all,

this is just a question: I was wondering, why test-code is shipped/deployed with the napari-plugin according to the template? On Java island, we typically have [two separate folders for production ("main") source files and "test" sources](https://stackoverflow.com/questions/49995270/difference-between-src-main-java-and-src-test-java-in-a-maven-project). Once one compiles a jar file for deployment, the test source are excluded. In that way, one can keep the shipped binary small. Github-CI also doesn't need the tests within the deployed file, because it builds from source anyway. 
In the napari cookiecutter template, the [_tests folder](https://github.com/napari/cookiecutter-napari-plugin/tree/main/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/_tests) lives within the production sources. I'm wondering why.

What's the benefits from shipping the tests with a plugin? Or is it possible to exclude test files from the deployment? Does that make sense? Any hints and links are welcome! 

Thanks,
Robert

**Comment by tlambert03** [comment]
This is a matter of preference.  In my other projects I actually leave tests outside of the source and don't include in sdist.

I believe @jni likes putting tests in sdist because it makes it very easy to test the pip installed package with [pytest --pyargs](https://docs.pytest.org/en/6.2.x/example/pythoncollection.html#interpreting-cmdline-arguments-as-python-packages).  This was done here to mimic the napari layout, but it's equally valid to leave them outside.

**Comment by tlambert03** [comment]
It's possible to exclude files from your sdist by modifying your MANIFEST.in. (Regardless of where they are in your package).  Though, personally, I'd probably just move the tests folder rather than modify manifest

**Comment by haesleinhuepf** [comment]
Thanks for the feedback Talley @tlambert03 ! Was suspecting that tests were outside src in earlier of the cookiecutter template, because some of my napari-plugins show that layout. Ok, if there is no hard reason to have the tests inside, I may also move that directory out of some of my plugins. I came across that issue because calling `pytest tests/test_something.py::test_something` is easier to type than `pytest my_complicated_package_name/_tests/test_something.py::test_something`, especialy on command lines that cannot auto-complete within folders (Windows) ;-)

Thanks again!

**Comment by tlambert03** [comment]
If you don't know the k flag in pytest you may also like that

pytest -k test_something 

https://docs.pytest.org/en/6.2.x/usage.html#specifying-tests-selecting-tests

**Comment by haesleinhuepf** [comment]
Oh, cool I didn't know that. Big thanks!
