### ISSUE TITLE
Make the npe2 cookiecutter the default

### ISSUE THREAD

**Issue by nclack** [napari/cookiecutter-napari-plugin#89]
Currently users invoke the npe2 cookiecutter by specifying a branch:

`cookiecutter https://github.com/napari/cookiecutter-napari-plugin --checkout npe2`.

Now that napari 0.4.13 is released, I'd like to 

1. move the main branch to a napari-plugin-engine branch
2. make npe2 the main branch

Doing this requires corresponding documentation updates in napari.

We don't _have_ to do this, but we tend to maintain the main branch first, and I'd like to encourage npe2 as the default.

**Comment by tlambert03** [comment]
sounds good to me.

**Comment by DragaDoncila** [comment]
Yep, I agree npe2 should be main
